services:
  influxdb:
    image: influxdb:2.6
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=motor_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-token
    volumes:
      - ./influxdb-data:/var/lib/influxdb2

  metrics-collector:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metrics-collector
    depends_on:
      - influxdb
    network_mode: host
    environment:
      - MQTT_BROKER=tcp://127.0.0.1:1883
      - MQTT_TOPIC1=web/input
      - MQTT_TOPIC2=controller/input
      - INFLUX_URL=http://127.0.0.1:8086
      - INFLUX_TOKEN=my-token
      - INFLUX_ORG=my-org
      - INFLUX_BUCKET=motor_data
    restart: unless-stopped
